spring:
  test:
    database:
      replace: none

  flyway:
    enabled: true

# ✅ Props reales del proyecto (evitan WeakKeyException)
app:
  security:
    jwtSecret: "this_is_a_super_long_test_secret_key_that_is_at_least_32_bytes_long"
    jwtTtlMinutes: 60

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: INFO
    org.flywaydb: INFO