apiVersion: 1

contactPoints:
  - orgId: 1
    name: Barmi Alerts Webhook
    receivers:
      - uid: barmi-alerts-webhook
        type: webhook
        settings:
          url: ${GRAFANA_ALERT_WEBHOOK_URL}
          httpMethod: POST
          username: ${GRAFANA_ALERT_WEBHOOK_USERNAME}
          title: ${GRAFANA_ALERT_WEBHOOK_TITLE}
          message: '{{ template "default.message" . }}'
        disableResolveMessage: false
