logging:
  level:
    root: INFO

spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

management:
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        default:
          include: readinessState,db,redis
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db,redis
        health:
          include: readinessState,db,redis
  endpoints:
    web:
      exposure:
        include: health,info,metrics
