export const routes = {
  root: '/',
  observabilitySmoke: '/__observability',
  login: '/auth/login',
  publicStorePattern: '/public/:slug',
  publicStore: (slug: string) => `/public/${slug}`,
  storeCheckout: '/store/checkout',
  storeCheckoutSuccess: '/store/checkout/success',
  storeOrders: '/store/orders',
  storeOrderDetail: '/store/orders/:orderId',
  storeOrderDetailPath: (orderId: string) => `/store/orders/${orderId}`,
  ecosystemHome: '/ecosystem',
  ecosystemCatalog: '/ecosystem/catalog',
  ecosystemStoresMap: '/ecosystem/stores/map',
  ecosystemCheckout: '/ecosystem/checkout',
  ecosystemCheckoutSuccess: '/ecosystem/checkout/success',
  ecosystemOrders: '/ecosystem/orders',
  ecosystemOrderDetail: '/ecosystem/orders/:orderId',
  ecosystemOrderDetailPath: (orderId: string) => `/ecosystem/orders/${orderId}`,
  adminHome: '/admin',
  adminOrders: '/admin/orders',
  adminOrderDetailPattern: '/admin/orders/:orderId',
  adminOrderDetail: (orderId: string) => `/admin/orders/${orderId}`,
  adminFulfillments: '/admin/fulfillments',
  adminFulfillmentDetailPattern: '/admin/fulfillments/:fulfillmentId',
  adminFulfillmentDetail: (fulfillmentId: string) => `/admin/fulfillments/${fulfillmentId}`,
  adminMembers: '/admin/members',
  adminStoreProducts: '/admin/store/products',
  adminStorePromotions: '/admin/store/promotions',
  adminShippingZones: '/admin/shipping/zones',
  adminStore: '/admin/store',
  adminEcosystem: '/admin/ecosystem',
  adminEcosystemOrders: '/admin/ecosystem/orders',
  adminEcosystemOrderDetailPattern: '/admin/ecosystem/orders/:orderId',
  adminEcosystemOrderDetail: (orderId: string) => `/admin/ecosystem/orders/${orderId}`,
  adminEcosystemFulfillments: '/admin/ecosystem/fulfillments',
  adminEcosystemFulfillmentDetailPattern: '/admin/ecosystem/fulfillments/:fulfillmentId',
  adminEcosystemFulfillmentDetail: (fulfillmentId: string) => `/admin/ecosystem/fulfillments/${fulfillmentId}`,
  adminEcosystemProducts: '/admin/ecosystem/products',
  adminEcosystemShipping: '/admin/ecosystem/shipping',
  adminEcosystemPromotions: '/admin/ecosystem/promotions'
} as const
