export const routes = {
  root: '/',
  login: '/auth/login',
  publicStorePattern: '/public/:slug',
  publicStore: (slug: string) => `/public/${slug}`,
  storeCheckout: '/store/checkout',
  storeCheckoutSuccess: '/store/checkout/success',
  storeOrders: '/store/orders',
  storeOrderDetail: '/store/orders/:orderId',
  storeOrderDetailPath: (orderId: string) => `/store/orders/${orderId}`,
  ecosystemCatalog: '/ecosystem',
  ecosystemCheckout: '/ecosystem/checkout',
  ecosystemCheckoutSuccess: '/ecosystem/checkout/success',
  ecosystemOrders: '/ecosystem/orders',
  ecosystemOrderDetail: '/ecosystem/orders/:orderId',
  ecosystemOrderDetailPath: (orderId: string) => `/ecosystem/orders/${orderId}`,
  adminHome: '/admin',
  adminOrders: '/admin/orders',
  adminOrderDetailPattern: '/admin/orders/:orderId',
  adminOrderDetail: (orderId: string) => `/admin/orders/${orderId}`,
  adminFulfillments: '/admin/fulfillments',
  adminFulfillmentDetailPattern: '/admin/fulfillments/:fulfillmentId',
  adminFulfillmentDetail: (fulfillmentId: string) => `/admin/fulfillments/${fulfillmentId}`,
  adminMembers: '/admin/members',
  adminShippingZones: '/admin/shipping/zones',
  adminStore: '/admin/store',
  adminEcosystem: '/admin/ecosystem',
  adminEcosystemProducts: '/admin/ecosystem/products',
  adminEcosystemShipping: '/admin/ecosystem/shipping'
} as const
